
// https://github.com/hashgraph/hedera-mirror-node/blob/main/hedera-mirror-rest/model/transactionType.js
// https://github.com/hashgraph/hedera-mirror-node-explorer/blob/main/src/utils/TransactionTools.ts

const transationTypeName: Record<number, string> = {
  7: 'Contract Call',
  8: 'Contract Create',
  9: 'Contract Update',
  10: 'Crypto Add Live Hash',
  11: 'Crypto Create Account',
  12: 'Crypto Delete Account',
  13: 'Crypto Delete Live Hash',
  14: 'Crypto Transfer',
  15: 'Crypto Update Account',
  16: 'File Append',
  17: 'File Create',
  18: 'File Delete',
  19: 'File Update',
  20: 'System Delete',
  21: 'System Undelete',
  22: 'Contract Delete',
  23: 'Freeze',
  24: 'HCS Create Topic',
  25: 'HCS Update Topic',
  26: 'HCS Delete Topic',
  27: 'HCS Submit Message',
  28: 'Unchecked Submit',
  29: 'Token Create',
  31: 'Token Freeze',
  32: 'Token Unfreeze',
  33: 'Token KYC Grant',
  34: 'Token KYC Revoke',
  35: 'Token Delete',
  36: 'Token Update',
  37: 'Token Mint',
  38: 'Token Burn',
  39: 'Token Wipe',
  40: 'Token Associate',
  41: 'Token Dissociate',
  42: 'Schedule Create',
  43: 'Schedule Delete',
  44: 'Schedule Sign',
  45: 'Token Fee Schedule Update',
  46: 'Token Pause',
  47: 'Token Unpause',
  48: 'Crypto Approve Allowance',
  49: 'Crypto Delete Allowance',
  50: 'Ethereum Transaction',
  51: 'Node Stake Update',
  52: 'Pseudorandom Number Generate',
  53: 'Token Update NFTs',
  54: 'Node Create',
  55: 'Node Update',
  56: 'Node Delete',
  57: 'Token Reject',
  58: 'Token Airdrop',
  59: 'Token Cancel Airdrop',
  60: 'Token Claim Airdrop',
};

//https://github.com/hashgraph/hedera-mirror-node/blob/1423952e5d5c8d582c8fcca4ee9d0d2f0dc1999e/hedera-mirror-rest/model/transactionResult.js#L42
const SUCCESS_RESULT = 22;

export { transationTypeName, SUCCESS_RESULT };